name: Ajjara
description: "an app that opens opportunities for companies to rent their machines in the construction industry."
publish_to: 'none'

version: 1.0.3+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 
  path: 
  mime: 
  uuid:
  go_router: 
  flutter_riverpod: 
  flutter_dotenv: 
  cached_network_image: 
  octo_image: 
  shimmer: 
  http:
  infinite_scroll_pagination: 
  form_validator: 
  intl: 
  timeago: 
  url_launcher: 
  image_picker: 
  file_picker: 
  flutter_image_compress: 
  path_provider: 
  open_filex: 
  flutter_secure_storage: 
  shared_preferences: 
  permission_handler: 
  firebase_core: 
  firebase_auth:
  firebase_messaging: 
  flutter_local_notifications: 
  google_maps_flutter: 
  logger: 
  sentry_flutter: 
  google_fonts: 
  pinput: 
  mask_text_input_formatter: 
  modal_bottom_sheet: 
  overlay_support: 
  photo_view: 
  carousel_slider: 
  dio_cache_interceptor: 
  dio_cache_interceptor_hive_store: 
  connectivity_plus: 
  dio_smart_retry: 
  pdfx: 
  share_plus: 
  geolocator: 
  geocoding: 
  #firebase_analytics: 
  app_links: 
  equatable: 
  riverpod_annotation: 
  workmanager: 
  iconsax_flutter:
  flutter_lucide:
  tabler_icons_next:
  iconoir_flutter:
  another_flushbar: 
  phosphor_flutter: 
  lucide_icons_flutter: 
  flex_color_scheme: 
  flutter_animate: 
  flutter_slidable: 
  sensors_plus: 
  dynamic_color: 
  provider: 
  flutter_gen: 
  syncfusion_flutter_calendar:
  #image_compression_flutter: 
  flutter_localizations:
    sdk: flutter
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 
  flutter_native_splash:
  flutter_launcher_icons:

  build_runner: 
  riverpod_generator: 
  shelf: ^1.4.1
  shelf_proxy: ^1.0.4

flutter:

  uses-material-design: true
  generate: true

  assets:
    - lib/assets/hero.jpg
    - lib/assets/alogo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/assets/alogo.png"
  web:
    generate: true
    image_path: "lib/assets/alogo.png"
    background_color: "#FFFFFF"
    theme_color: "#FFFFFF"
  windows:
    generate: true
    image_path: "lib/assets/alogo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "lib/assets/alogo.png"

# Native splash screen configuration
flutter_native_splash:
  # Global settings
  color: "#FFFFFF"            # Background color (light)
  image: lib/assets/alogo.png      # Center image for splash (provide a transparent PNG if possible)
  # Optional: Dark theme background
  color_dark: "#121212"
  image_dark: lib/assets/alogo.png

  # Android 12+ requires a separate section
  android_12:
    color: "#FFFFFF"
    image: lib/assets/alogo.png
    color_dark: "#121212"
    image_dark: lib/assets/alogo.png

  android: true
  ios: true
  web: true

  # Optional tuning
  fullscreen: true             # Hide status bar during splash
  # You can adjust positioning if needed:
  # android_gravity: center
  # ios_content_mode: center


